### ISSUE TITLE
Levels--

### ISSUE THREAD

**Issue by Sbte** [nlesc-smcm/hymls#12]
The "levels" as defined in HYMLS are confusing, since in the code, 1 level means solving the schur complement directly, 2 levels means performing the Householder transformation, dropping, and then elimination, and 3 levels means performing this last step twice. It could have also meant that 3 levels meant performing the householder transformation once, then again computing a new Schur complement and then doing a direct solve, and 4 levels mean performing the Householder transformation etc. twice. For consistency, we want to make it that a level instead means the amount of times the Householder transformation and dropping step was performed, which means that the method that was previously called the two level method is then the 1 level method.

**Comment by jthies** [comment]
it seems to me that in exact arithmetic it doesn't matter if you do a direct factorization in two steps (reduce to separators, factor Schur complement), so some of the variants would be equivalent?

**Comment by Sbte** [comment]
True. The difference would be that you use HYMLS to parallelize the direct solve. But at the moment we do not implement it like this, which is why I suggest we rename the levels such that 1 level always means you apply the Householder transformation and dropping once. We can still keep "level 0" as HYMLS as direct solver for testing purposes, but in general you do not need this, since you can set either "Apply Dropping" to false or retain all nodes after a certain level with the "Retain Nodes at Level x" parameters. This will give the exact same effect as applying a direct solver, since every node will be considered a Vsum node.

**Comment by jthies** [comment]
fine with me, indeed, the option to use it as a direct solver should remain as "level 0"
